name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: npm install
      run: npm install
    - name: Action ESLint
      uses: sibiraj-s/action-eslint@v2.0.0
    - name: Create Test
      run: ./create_tests.sh
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
      with:
        jestArgs: ./All.test.js  -c ./jest.config.js --silent=false --verbose false